### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by pombredanne** [spacehackers/topstories#2]
What would be the license for your fine code?

**Comment by basilleaf** [comment]
here we go https://github.com/spacehackers/topstories/blob/master/LICENSE

**Comment by pombredanne** [comment]
@basilleaf thanks!
But note that if there ever was such thing as a license and copyright compiler, https://github.com/spacehackers/topstories/blob/master/LICENSE#L3 would likely fail with these messages:

```
Line 3: Copyright (c) [year] [fullname]
Compilation error: Unrecognized variable [year]

Line 3: Copyright (c) [year] [fullname]
Compilation error: Unrecognized variable [fullname]

Compilation failed.
```

**Comment by basilleaf** [comment]
oh thank you for catching that, I added a year and my name.

**Comment by pombredanne** [comment]
excellent! thx :)
